site_name: Mongo Bakery
site_url: https://mongo-bakery.github.io/mongo_bakery/
repo_url: https://github.com/mongo-bakery/mongo_bakery
repo_name: mongo_bakery
edit_uri: tree/main/docs

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: material
  logo: assets/logoMongoBakery.png
  favicon: assets/logoMongoBakery.png
  palette:
    primary: white
    accent: indigo
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            docstring_style: google
